### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by JBetts97** [JBetts97/ShedShare#1]
**Here is the functionality I would like to add to this project:**

- [ ] Allow user to show and update profile Image on ProfileView.swift
- [ ] Decide on firestore db infrastructure for users tools (what fields should there be ect.)
- [ ] Create view for 'Your Tools' btn on ProfileView.swift (must allow user to add tools to db)
- [ ] Create view for 'Your Profile' btn on ProfileView.swift (to allow user to modify name/location etc)
- [ ] Create view for 'Find nearby tools' btn on ProfileView.swift (to search db and allow tool borrow)
- [ ] Create view for 'Browse Favourites' btn on ProfileView.swift (to search bookmarked db records)

**Comment by JBetts97** [comment]
Trello board (in sync with this issue page) available here: https://trello.com/b/b9zWuBKU/shed-app
